package com.nspace.mediacenter.util;

import java.util.Arrays;

/**
 * Runtime key vault.
 *
 * <p>The AES-256-GCM keys are deliberately NOT shipped as a single literal
 * string in {@code classes.dex} — that would let a trivial regular expression
 * over the APK extract them (as the security audit demonstrated). Instead each
 * key is split into 8 fragments, permuted by a fixed order, and XOR-masked with
 * a 32-byte constant; the real key bytes are reconstructed only at runtime and
 * cached. Combined with {@link AppIntegrity} (self-signature verification), this
 * raises the cost of key extraction far beyond a single grep over the binary.
 *
 * <p>The obfuscation material here is generated by {@code _gen_secrets.py} and is
 * build-time derived from the keys in {@code local.properties}; it is NOT the
 * plaintext key. Rotate keys by re-running that script.
 */
public final class KeyVault {

  // ── region_apps_config.enc key material (obfuscated) ──
  private static final String[] CFG_FRAGS = {
      "f7060907", "f84dd090", "1dff947e", "fc4cbd00",
      "fd8cb2f3", "38759b46", "7ab9416c", "4d2a6fc2"
  };
  private static final int[] CFG_ORDER = { 4, 5, 7, 1, 0, 6, 3, 2 };
  private static final String CFG_MASK =
      "0a8abbf4c0384bd650d5fbbc04016d900a8abbf442ccda2a86f5fc6c50d5fbbc";

  // ── remote vin.enc key material (obfuscated) ──
  private static final String[] VIN_FRAGS = {
      "8ac1ac62", "bfcaee40", "46144dff", "9ee77706",
      "b95ed407", "fb15021b", "7b1f9e14", "0600ac3d"
  };
  private static final int[] VIN_ORDER = { 0, 3, 5, 4, 1, 6, 7, 2 };
  private static final String VIN_MASK =
      "00000000212d9946bd014fe427b9a30106943a47800a9c0f7d1f32294014e1c2";

  private static volatile byte[] sCfg;
  private static volatile byte[] sVin;

  private KeyVault() {
  }

  /** AES-256 key (32 bytes) for decrypting {@code region_apps_config.enc}. */
  public static byte[] configKey() {
    if (sCfg == null) {
      synchronized (KeyVault.class) {
        if (sCfg == null) sCfg = reconstruct(CFG_FRAGS, CFG_ORDER, CFG_MASK);
      }
    }
    return sCfg;
  }

  /** AES-256 key (32 bytes) for decrypting the remote per-VIN revocation file. */
  public static byte[] vinRemoteKey() {
    if (sVin == null) {
      synchronized (KeyVault.class) {
        if (sVin == null) sVin = reconstruct(VIN_FRAGS, VIN_ORDER, VIN_MASK);
      }
    }
    return sVin;
  }

  /**
   * Base URL for the remote per-VIN revocation allowlist. This is a public
   * endpoint (not a secret), shipped as a plain constant.
   */
  public static String vinRemoteUrl() {
    return "https://www.cyaispace.tech/vin/";
  }

  /** Reassemble fragments by {@code order}, then XOR with {@code maskHex}. */
  private static byte[] reconstruct(String[] frags, int[] order, String maskHex) {
    StringBuilder sb = new StringBuilder(frags.length * 8);
    for (int idx : order) sb.append(frags[idx]);
    byte[] hex = hexToBytes(sb.toString());
    byte[] mask = hexToBytes(maskHex);
    byte[] out = new byte[Math.min(hex.length, mask.length)];
    for (int i = 0; i < out.length; i++) {
      out[i] = (byte) (hex[i] ^ mask[i]);
    }
    return out;
  }

  private static byte[] hexToBytes(String s) {
    int len = s.length();
    byte[] out = new byte[len / 2];
    for (int i = 0; i < out.length; i++) {
      out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
    }
    return out;
  }
}
